# Config settings



# Tools we need
CUSTOMTOOL=/ece566/projects/p2/C++/build
CUSTOMCODEGEN=
FAULTINJECTTOOL=
PROFILER=
P1TOOL=true
P2TOOL=
CLANG=/usr/bin/clang-14
OPT=/usr/bin/opt-14
LLC=/usr/bin/llc-14
LLVMAS=/usr/bin/llvm-as-14
LLVM_LINK=/usr/bin/llvm-link-14
LLVM_CONFIG=/usr/bin/llvm-config-14
LLVM_DIS=/usr/bin/llvm-dis-14
DRAGONEGG=
GCC=/usr/bin/gcc

LIBS=
PLIBS=`cd /ece566/wolfbench/../projects/install/lib/; pwd`/librt.a `$(LLVM_CONFIG) --libdir`/libprofile_rt.a

RUN=/ece566/wolfbench/RunSafelyAndStable.sh 60 1 

DIFF=/ece566/wolfbench/RunDiff.sh

EXTRA_SUFFIX=

ifdef DEBUG
CFLAGS+=-g
endif
